# Generated by Django 3.0.8 on 2020-07-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Frames', 'frames'), ('Others', 'others')], max_length=50)),
                ('location', models.TextField()),
            ],
        ),
    ]
